Update functions.R
jgockley62/sageseqr pull request #2
Opened 2021-09-10 22:30 UTC by jgockley62

Added BPPARAM = BiocParallel::SnowParam(parallel::detectCores()-1) to variancePartition::dream and variancePartition::voomWithDreamWeights function calls

2021-09-10 22:46 UTC, kelshmo requested changes
I think this should work OK. We also need to declare `parallel` and `BiocParallel` as imports in the DESCRIPTION file. Have you tested whether this works in a fresh environment?

2021-09-14 00:28 UTC, jgockley62 commented
@kelshmo Implements pulling the number of cores from the config directly. If NULL cores is set to: ```parallel::detectCores()-1```

2021-09-14 22:51 UTC, kelshmo requested changes
Can you run `devtools::document()` and commit the new documentation in the man/ folder? I can't test the function until you do that.

There are some small suggested changes to syntax.

2021-09-14 22:51 UTC, kelshmo commented on R/functions.R
> +#' @param cores An integer of cores to specify in the parallel backend (eg. 4)
```suggestion
#' @param cores An integer of cores to specify in the parallel backend (eg. 4).
```

2021-09-14 22:51 UTC, kelshmo commented on R/functions.R
> +#'
```suggestion
#'
```

2021-09-14 22:51 UTC, kelshmo commented on vignettes/customize-config.Rmd
> +                  BiocParallelDoparParam, and SerialParam not currently supported.
```suggestion
                  BiocParallelDoparParam, and SerialParam are not currently supported.
```

2021-09-15 03:36 UTC, jgockley62 commented
@kelshmo Suggestions implemented and devtools::document() run with new manual pages pushed as welld

2021-09-15 17:01 UTC, kelshmo commented
@jgockley62 `wrap_de` is missing the cores parameter. You will also need to commit the man/ files for that function.

2021-09-15 17:49 UTC, jgockley62 commented
@kelshmo whoops my bad should be added

2021-09-15 22:57 UTC, kelshmo approved these changes

2021-09-15 22:57 UTC, kelshmo commented
This works! I tested omitting parameters and manually setting. Well done!

2021-09-15 23:24 UTC, merged